# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PunkeBeerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
pod 'Alamofire'
pod 'JGProgressHUD'
pod 'SDWebImage'
pod 'SwiftMessages'
pod 'SwiftyJSON'

  # Pods for PunkeBeerApp

  target 'PunkeBeerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PunkeBeerAppUITests' do
    # Pods for testing
  end

end
